/* =========================================================
   DE_HAKEM_KLASMAN DUMMY DATA
   1  = TFF
   2  = TBF
   3  = TVF
   ========================================================= */


/* =========================================================
   1. IDENTITY ALANINI ELLE ID KABUL EDECEK HALE GETIR
   ========================================================= */

ALTER TABLE DE_HAKEM_KLASMAN
MODIFY (
    KLASMAN_ID GENERATED BY DEFAULT AS IDENTITY
);


/* =========================================================
   NOT:
   Tabloda eski veri varsa ve DE_HAKEMLER tablosundan
   FK ile bagli kayit yoksa asagidaki kodu calistirabilirsin.

   DELETE FROM DE_HAKEM_KLASMAN;
   COMMIT;
   ========================================================= */


/* =========================================================
   2. HAKEM KLASMANLARINI EKLE
   ========================================================= */

INSERT ALL

    /* =========================
       FUTBOL FEDERASYONU - TFF
       FEDERASYON_ID = 1
       ========================= */

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        1,
        1,
        'Üst Klasman Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        2,
        1,
        'Video Yardýmcý Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        3,
        1,
        'Üst Klasman Yardýmcý Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        4,
        1,
        'Klasman Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        5,
        1,
        'Klasman Yardýmcý Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        6,
        1,
        'Bölgesel Hakem'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        7,
        1,
        'Bölgesel Yardýmcý Hakem'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        8,
        1,
        'Kadýn Bölgesel Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        9,
        1,
        'Kadýn Bölgesel Yardýmcý Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        10,
        1,
        'Ýl Hakemi'
    )


    /* =========================
       BASKETBOL FEDERASYONU - TBF
       FEDERASYON_ID = 2
       ========================= */

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        11,
        2,
        'A Klasmaný Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        12,
        2,
        'B Klasmaný Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        13,
        2,
        'C Klasmaný Hakemi'
    )


    /* =========================
       VOLEYBOL FEDERASYONU - TVF
       FEDERASYON_ID = 3
       ========================= */

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        14,
        3,
        'A Klasman Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        15,
        3,
        'AB Klasman Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        16,
        3,
        'B Klasman Hakemi'
    )

    INTO DE_HAKEM_KLASMAN (
        KLASMAN_ID,
        FEDERASYON_ID,
        KLASMAN_TURU
    )
    VALUES (
        17,
        3,
        'C Klasman Hakemi'
    )

SELECT 1
FROM DUAL;


/* =========================================================
   3. KAYDET
   ========================================================= */

COMMIT;


/* =========================================================
   4. IDENTITY'YI TEKRAR OTOMATIK HALE GETIR

   Mevcut en buyuk KLASMAN_ID = 17 oldugu icin
   sonraki otomatik ID 18'den devam eder.
   ========================================================= */

ALTER TABLE DE_HAKEM_KLASMAN
MODIFY (
    KLASMAN_ID GENERATED ALWAYS AS IDENTITY
    (START WITH LIMIT VALUE)
);


/* =========================================================
   5. KONTROL
   ========================================================= */

SELECT
    KLASMAN_ID,
    FEDERASYON_ID,
    KLASMAN_TURU,
    ISLEM_TARIHI
FROM DE_HAKEM_KLASMAN
ORDER BY KLASMAN_ID;
