INSERT INTO DE_MUSABAKA_ALANI (
    FEDERASYON_ID,
    MUSABAKA_ALANI_ADI,
    MUSABAKA_ALANI_ADRESI,
    MUSABAKA_ALANI_SEHIR,
    MUSABAKA_ALANI_KAPASITE,
    ZEMIN_TURU,
    TAKIM_ID
)
SELECT 1 AS FEDERASYON_ID, 'Diyarbakýr Stadyumu' AS MUSABAKA_ALANI_ADI, 'Talaytepe Mah., Kayapýnar' AS MUSABAKA_ALANI_ADRESI, 'Diyarbakýr' AS MUSABAKA_ALANI_SEHIR, 33000 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 1 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Tüpraþ Stadyumu' AS MUSABAKA_ALANI_ADI, 'Viþnezade Mah., Dolmabahçe Cd., Beþiktaþ' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 42590 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 2 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'GAIN Park Stadyumu' AS MUSABAKA_ALANI_ADI, 'Saray Mah., Alanya' AS MUSABAKA_ALANI_ADRESI, 'Antalya' AS MUSABAKA_ALANI_SEHIR, 10128 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 3 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Çaykur Didi Stadyumu' AS MUSABAKA_ALANI_ADI, 'Engindere Mah., Merkez' AS MUSABAKA_ALANI_ADRESI, 'Rize' AS MUSABAKA_ALANI_SEHIR, 15332 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 4 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Çorum Þehir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Mimar Sinan Mah., Merkez' AS MUSABAKA_ALANI_ADRESI, 'Çorum' AS MUSABAKA_ALANI_SEHIR, 15000 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 5 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Kazým Karabekir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Kazým Karabekir Mah., Yakutiye' AS MUSABAKA_ALANI_ADRESI, 'Erzurum' AS MUSABAKA_ALANI_SEHIR, 23700 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 6 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Recep Tayyip Erdoðan Stadyumu' AS MUSABAKA_ALANI_ADI, 'Kaptanpaþa Mah., Kasýmpaþa, Beyoðlu' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 14234 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 7 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Chobani Stadyumu Fenerbahçe Þükrü Saracoðlu Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Zühtüpaþa Mah., Baðdat Cd., Kadýköy' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 47834 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 8 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Ali Sami Yen Spor Kompleksi RAMS Park' AS MUSABAKA_ALANI_ADI, 'Huzur Mah., Seyrantepe, Sarýyer' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 52280 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 9 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Gaziantep Büyükþehir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Beylerbeyi Mah., Þehitkamil' AS MUSABAKA_ALANI_ADRESI, 'Gaziantep' AS MUSABAKA_ALANI_SEHIR, 35574 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 10 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Eryaman Stadyumu' AS MUSABAKA_ALANI_ADI, 'Eryaman Mah., Etimesgut' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 20560 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 11 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Gürsel Aksel Stadyumu' AS MUSABAKA_ALANI_ADI, 'Mehmet Ali Akman Mah., Konak' AS MUSABAKA_ALANI_ADRESI, 'Ýzmir' AS MUSABAKA_ALANI_SEHIR, 19219 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 12 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Baþakþehir Fatih Terim Stadyumu' AS MUSABAKA_ALANI_ADI, 'Baþak Mah., Baþakþehir' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 17156 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 13 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Recep Tayyip Erdoðan Stadyumu' AS MUSABAKA_ALANI_ADI, 'Kaptanpaþa Mah., Kasýmpaþa, Beyoðlu' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 14234 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 14 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Kocaeli Stadyumu' AS MUSABAKA_ALANI_ADI, 'Alikahya Atatürk Mah., Ýzmit' AS MUSABAKA_ALANI_ADRESI, 'Kocaeli' AS MUSABAKA_ALANI_SEHIR, 34712 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 15 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'MEDAÞ Konya Büyükþehir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Selçuklu Mah., Selçuklu' AS MUSABAKA_ALANI_ADRESI, 'Konya' AS MUSABAKA_ALANI_SEHIR, 42276 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 16 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Samsun Yeni 19 Mayýs Stadyumu' AS MUSABAKA_ALANI_ADI, 'Tekkeköy' AS MUSABAKA_ALANI_ADRESI, 'Samsun' AS MUSABAKA_ALANI_SEHIR, 33919 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 17 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Papara Park' AS MUSABAKA_ALANI_ADI, 'Akyazý Mah., Ortahisar' AS MUSABAKA_ALANI_ADRESI, 'Trabzon' AS MUSABAKA_ALANI_SEHIR, 40782 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 18 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Bolu Atatürk Stadyumu' AS MUSABAKA_ALANI_ADI, 'Karaçayýr Mah., Merkez' AS MUSABAKA_ALANI_ADRESI, 'Bolu' AS MUSABAKA_ALANI_SEHIR, 8881 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 19 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Manisa 19 Mayýs Stadyumu' AS MUSABAKA_ALANI_ADI, 'Þehzadeler' AS MUSABAKA_ALANI_ADRESI, 'Manisa' AS MUSABAKA_ALANI_SEHIR, 16597 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 20 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Bandýrma 17 Eylül Stadyumu' AS MUSABAKA_ALANI_ADI, 'Paþabayýr Mah., Bandýrma' AS MUSABAKA_ALANI_ADRESI, 'Balýkesir' AS MUSABAKA_ALANI_SEHIR, 12725 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 21 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Esenyurt Necmi Kadýoðlu Stadyumu' AS MUSABAKA_ALANI_ADI, 'Zafer Mah., Esenyurt' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 4488 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 22 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Corendon Airlines Park Antalya Stadyumu' AS MUSABAKA_ALANI_ADI, 'Meltem Mah., Muratpaþa' AS MUSABAKA_ALANI_ADRESI, 'Antalya' AS MUSABAKA_ALANI_SEHIR, 32537 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 23 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Aktepe Stadyumu' AS MUSABAKA_ALANI_ADI, 'Aktepe Mah., Keçiören' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 4883 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 24 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'BG Grup 4 Eylül Stadyumu' AS MUSABAKA_ALANI_ADI, 'Muhsin Yazýcýoðlu Bulvarý, Merkez' AS MUSABAKA_ALANI_ADRESI, 'Sivas' AS MUSABAKA_ALANI_SEHIR, 27532 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 25 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Esenler Erokspor Stadyumu' AS MUSABAKA_ALANI_ADI, 'Kemer Mah., Esenler' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 5296 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 26 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Ümraniye Belediyesi Þehir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Hekimbaþý Mah., Ümraniye' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 3513 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 27 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, '21 Kasým Þehir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Artuklu' AS MUSABAKA_ALANI_ADRESI, 'Mardin' AS MUSABAKA_ALANI_SEHIR, 5700 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 28 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Yusuf Ziya Öniþ Stadyumu' AS MUSABAKA_ALANI_ADI, 'Tarabya Mah., Sarýyer' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 4100 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 29 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Muðla Atatürk Stadyumu' AS MUSABAKA_ALANI_ADI, 'Muslihittin Mah., Menteþe' AS MUSABAKA_ALANI_ADRESI, 'Muðla' AS MUSABAKA_ALANI_SEHIR, 7750 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 30 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Van Atatürk Þehir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Ýpekyolu' AS MUSABAKA_ALANI_ADRESI, 'Van' AS MUSABAKA_ALANI_SEHIR, 10500 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 31 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'RHg Enertürk Enerji Stadyumu' AS MUSABAKA_ALANI_ADI, 'Kadir Has Kongre ve Spor Merkezi yaný, Kocasinan' AS MUSABAKA_ALANI_ADRESI, 'Kayseri' AS MUSABAKA_ALANI_SEHIR, 32864 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 32 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Bodrum Ýlçe Stadyumu' AS MUSABAKA_ALANI_ADI, 'Yokuþbaþý Mah., Bodrum' AS MUSABAKA_ALANI_ADRESI, 'Muðla' AS MUSABAKA_ALANI_SEHIR, 4563 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 33 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Bursa Büyükþehir Belediye Stadyumu' AS MUSABAKA_ALANI_ADI, 'Veledrom Cad., Osmangazi' AS MUSABAKA_ALANI_ADRESI, 'Bursa' AS MUSABAKA_ALANI_SEHIR, 43761 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 34 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Iðdýr Þehir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Baðlar Mah., Merkez' AS MUSABAKA_ALANI_ADRESI, 'Iðdýr' AS MUSABAKA_ALANI_SEHIR, 6500 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 35 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Atatürk Olimpiyat Stadyumu' AS MUSABAKA_ALANI_ADI, 'Ýkitelli, Baþakþehir' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 76092 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 36 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Pendik Stadyumu' AS MUSABAKA_ALANI_ADI, 'Batý Mah., Pendik' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 37 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 1 AS FEDERASYON_ID, 'Batman Yeni Þehir Stadyumu' AS MUSABAKA_ALANI_ADI, 'Yeniþehir Mah., Merkez' AS MUSABAKA_ALANI_ADRESI, 'Batman' AS MUSABAKA_ALANI_SEHIR, 15000 AS MUSABAKA_ALANI_KAPASITE, 'Doðal Çim' AS ZEMIN_TURU, 38 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Ülker Spor ve Etkinlik Salonu' AS MUSABAKA_ALANI_ADI, 'Barbaros Mah., Ihlamur Blv., Ataþehir' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 13800 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 39 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Ülker Spor ve Etkinlik Salonu' AS MUSABAKA_ALANI_ADI, 'Barbaros Mah., Ihlamur Blv., Ataþehir' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 13800 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 40 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Basketbol Geliþim Merkezi' AS MUSABAKA_ALANI_ADI, 'Zeytinburnu' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 10000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 41 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Çayýrova Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Akse Mah., Çayýrova' AS MUSABAKA_ALANI_ADRESI, 'Kocaeli' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 42 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Ankara Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Doðanbey Mah., Altýndað' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 10400 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 43 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Mustafa Kemal Atatürk Karþýyaka Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Maviþehir, Karþýyaka' AS MUSABAKA_ALANI_ADRESI, 'Ýzmir' AS MUSABAKA_ALANI_SEHIR, 5000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 44 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Hayri Gür Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Soðuksu Mah., Ortahisar' AS MUSABAKA_ALANI_ADRESI, 'Trabzon' AS MUSABAKA_ALANI_SEHIR, 7500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 45 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Tofaþ Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Demirtaþ Dumlupýnar OSB, Osmangazi' AS MUSABAKA_ALANI_ADRESI, 'Bursa' AS MUSABAKA_ALANI_SEHIR, 7500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 46 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Basketbol Geliþim Merkezi' AS MUSABAKA_ALANI_ADI, 'Zeytinburnu' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 10000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 47 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'BJK Fibabanka Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Akat Mah., Beþiktaþ' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 3200 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 48 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Tofaþ Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Demirtaþ Dumlupýnar OSB, Osmangazi' AS MUSABAKA_ALANI_ADRESI, 'Bursa' AS MUSABAKA_ALANI_SEHIR, 7500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 49 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Banvit Kara Ali Acar Spor Salonu' AS MUSABAKA_ALANI_ADI, '17 Eylül Mah., Bandýrma' AS MUSABAKA_ALANI_ADRESI, 'Balýkesir' AS MUSABAKA_ALANI_SEHIR, 3000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 50 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'ENKA Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Siteler Mah., Aliaða' AS MUSABAKA_ALANI_ADRESI, 'Ýzmir' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 51 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Pamukkale Üniversitesi Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Kýnýklý Kampüsü, Pamukkale' AS MUSABAKA_ALANI_ADRESI, 'Denizli' AS MUSABAKA_ALANI_SEHIR, 5000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 52 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Körfez Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Körfez' AS MUSABAKA_ALANI_ADRESI, 'Kocaeli' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 53 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Esenler Mehmet Öcalan Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Turgut Reis Mah., Esenler' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 54 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Bornova Belediyesi Atatürk Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Kazýmdirik Mah., Bornova' AS MUSABAKA_ALANI_ADRESI, 'Ýzmir' AS MUSABAKA_ALANI_SEHIR, 3000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 55 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Kahramanmaraþ Merkez Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Onikiþubat' AS MUSABAKA_ALANI_ADRESI, 'Kahramanmaraþ' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 56 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Gazanfer Bilge Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Fatih Mah., Büyükçekmece' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 3000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 57 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'M. Sait Zarifoðlu Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Çankaya' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 58 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, '90. Yýl Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Merkez' AS MUSABAKA_ALANI_ADRESI, 'Yalova' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 59 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'TOBB ETÜ Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Söðütözü, Çankaya' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 60 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Basketbol Geliþim Merkezi' AS MUSABAKA_ALANI_ADI, 'Zeytinburnu' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 10000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 61 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Konya Spor ve Kongre Merkezi' AS MUSABAKA_ALANI_ADI, 'Selçuklu' AS MUSABAKA_ALANI_ADRESI, 'Konya' AS MUSABAKA_ALANI_SEHIR, 10000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 62 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Naim Süleymanoðlu Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Yýldýrým' AS MUSABAKA_ALANI_ADRESI, 'Bursa' AS MUSABAKA_ALANI_SEHIR, 3000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 63 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'BJK Fibabanka Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Akat Mah., Beþiktaþ' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 3200 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 64 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Baðlum Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Baðlum, Keçiören' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 65 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Karataþ Þahinbey Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Þahinbey' AS MUSABAKA_ALANI_ADRESI, 'Gaziantep' AS MUSABAKA_ALANI_SEHIR, 6400 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 66 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Kurtdereli Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Karesi' AS MUSABAKA_ALANI_ADRESI, 'Balýkesir' AS MUSABAKA_ALANI_SEHIR, 3000 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 67 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Fenerbahçe Metro Enerji Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Dereaðzý, Kadýköy' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 68 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'TOBB ETÜ Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Söðütözü, Çankaya' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 69 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Darüþþafaka Ayhan Þahenk Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Maslak, Sarýyer' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 3500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 70 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 2 AS FEDERASYON_ID, 'Servet Tazegül Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Yeniþehir' AS MUSABAKA_ALANI_ADRESI, 'Mersin' AS MUSABAKA_ALANI_SEHIR, 7500 AS MUSABAKA_ALANI_KAPASITE, 'Parke' AS ZEMIN_TURU, 71 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Aksaray Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Merkez' AS MUSABAKA_ALANI_ADRESI, 'Aksaray' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 72 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Prof. Dr. Veysel Eroðlu Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Merkez' AS MUSABAKA_ALANI_ADRESI, 'Afyonkarahisar' AS MUSABAKA_ALANI_SEHIR, 2800 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 73 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Burhan Felek Vestel Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Altunizade, Üsküdar' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 7000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 74 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Tarýk Almýþ Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Yunusemre' AS MUSABAKA_ALANI_ADRESI, 'Manisa' AS MUSABAKA_ALANI_SEHIR, 3500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 75 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Burhan Felek Vestel Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Altunizade, Üsküdar' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 7000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 76 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Burhan Felek Vestel Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Altunizade, Üsküdar' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 7000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 77 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'VakýfBank Spor Sarayý' AS MUSABAKA_ALANI_ADI, 'Üsküdar' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 2000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 78 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'BJK Fibabanka Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Akat Mah., Beþiktaþ' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 3200 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 79 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Cengiz Göllü Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Nilüfer' AS MUSABAKA_ALANI_ADRESI, 'Bursa' AS MUSABAKA_ALANI_SEHIR, 5000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 80 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Eczacýbaþý Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Kartal' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 4000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 81 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'TVF Ziraat Bankkart Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Beþtepe, Yenimahalle' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 82 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Bornova Belediyesi Atatürk Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Kazýmdirik Mah., Bornova' AS MUSABAKA_ALANI_ADRESI, 'Ýzmir' AS MUSABAKA_ALANI_SEHIR, 3000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 83 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Atatürk Voleybol Salonu Vestel Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Alsancak, Konak' AS MUSABAKA_ALANI_ADRESI, 'Ýzmir' AS MUSABAKA_ALANI_SEHIR, 6000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 84 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'TVF Ziraat Bankkart Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Beþtepe, Yenimahalle' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 85 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Atatürk Voleybol Salonu Vestel Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Alsancak, Konak' AS MUSABAKA_ALANI_ADRESI, 'Ýzmir' AS MUSABAKA_ALANI_SEHIR, 6000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 86 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'TVF Ziraat Bankkart Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Beþtepe, Yenimahalle' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 87 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Burhan Felek Vestel Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Altunizade, Üsküdar' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 7000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 88 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'TVF Ziraat Bankkart Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Beþtepe, Yenimahalle' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 89 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'TVF Ziraat Bankkart Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Beþtepe, Yenimahalle' AS MUSABAKA_ALANI_ADRESI, 'Ankara' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 90 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Burhan Felek Vestel Voleybol Salonu' AS MUSABAKA_ALANI_ADI, 'Altunizade, Üsküdar' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 7000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 91 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'ÝBB Cebeci Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Cebeci, Sultangazi' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 92 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Þahinbey Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Þahinbey' AS MUSABAKA_ALANI_ADRESI, 'Gaziantep' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 93 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Kahramanmaraþ Merkez Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Onikiþubat' AS MUSABAKA_ALANI_ADRESI, 'Kahramanmaraþ' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 94 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Gebze Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Gebze' AS MUSABAKA_ALANI_ADRESI, 'Kocaeli' AS MUSABAKA_ALANI_SEHIR, 3000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 95 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Sultanbeyli Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Sultanbeyli' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 2000 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 96 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Alanya 100. Yýl Recep Hacýfazlýoðlu Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Alanya' AS MUSABAKA_ALANI_ADRESI, 'Antalya' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 97 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'Sungurlu Mahmut Atalay Spor Salonu' AS MUSABAKA_ALANI_ADI, 'Sungurlu' AS MUSABAKA_ALANI_ADRESI, 'Çorum' AS MUSABAKA_ALANI_SEHIR, 1500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 98 AS TAKIM_ID FROM DUAL
UNION ALL
SELECT 3 AS FEDERASYON_ID, 'ÝBB Cebeci Spor Kompleksi' AS MUSABAKA_ALANI_ADI, 'Cebeci, Sultangazi' AS MUSABAKA_ALANI_ADRESI, 'Ýstanbul' AS MUSABAKA_ALANI_SEHIR, 2500 AS MUSABAKA_ALANI_KAPASITE, 'Taraflex' AS ZEMIN_TURU, 99 AS TAKIM_ID FROM DUAL;

COMMIT;

-- KONTROL
SELECT
    MUSABAKA_ALANI_ID,
    FEDERASYON_ID,
    MUSABAKA_ALANI_ADI,
    MUSABAKA_ALANI_SEHIR,
    MUSABAKA_ALANI_KAPASITE,
    ZEMIN_TURU,
    TAKIM_ID,
    ISLEM_TARIHI
FROM DE_MUSABAKA_ALANI
ORDER BY MUSABAKA_ALANI_ID;
