INSERT INTO DE_ORTAK_MUSABAKA_ALANI (
    ORTAK_GRUP_NO,
    MUSABAKA_ALANI_ID,
    MUSABAKA_ALANI_ADI,
    TAKIM_ID,
    TAKIM_ADI
)

SELECT
    DENSE_RANK() OVER (
        ORDER BY
            UPPER(TRIM(M.MUSABAKA_ALANI_ADI)),
            UPPER(TRIM(M.MUSABAKA_ALANI_ADRESI))
    ) AS ORTAK_GRUP_NO,

    M.MUSABAKA_ALANI_ID,

    M.MUSABAKA_ALANI_ADI,

    M.TAKIM_ID,

    T.TAKIM_ADI

FROM DE_MUSABAKA_ALANI M

JOIN DE_TAKIMLAR T
    ON T.TAKIM_ID = M.TAKIM_ID

WHERE M.TAKIM_ID IS NOT NULL

  AND EXISTS (

        SELECT 1
        FROM DE_MUSABAKA_ALANI M2

        WHERE M2.MUSABAKA_ALANI_ID <> M.MUSABAKA_ALANI_ID

          AND UPPER(TRIM(M2.MUSABAKA_ALANI_ADI))
              = UPPER(TRIM(M.MUSABAKA_ALANI_ADI))

          AND UPPER(TRIM(M2.MUSABAKA_ALANI_ADRESI))
              = UPPER(TRIM(M.MUSABAKA_ALANI_ADRESI))

          AND M2.TAKIM_ID <> M.TAKIM_ID
  );

COMMIT;
