/* =========================================================
   1. FEDERASYONLAR
   ========================================================= */

CREATE TABLE DE_FEDERASYONLAR (
    FEDERASYON_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ADI VARCHAR2(100) NOT NULL,
    FEDERASYON_BASKANI VARCHAR2(100) NOT NULL,
    FEDERASYON_BASKAN_YARDIMCISI VARCHAR2(100) NOT NULL,
    FEDERASYON_ADRESI VARCHAR2(250) NOT NULL,
    FEDERASYON_KURULUS_TARIHI NUMBER(4) NOT NULL,
    FEDERASYON_MAIL_ADRESI VARCHAR2(150) NOT NULL,
    FEDERASYON_WEB_SITESI VARCHAR2(200) NOT NULL,

    CONSTRAINT PK_DE_FEDERASYONLAR
        PRIMARY KEY (FEDERASYON_ID)
);


/* =========================================================
   2. LIGLER
   ========================================================= */

CREATE TABLE DE_LIGLER (
    LIG_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ID NUMBER NOT NULL,
    LIG_ADI VARCHAR2(100) NOT NULL,
    LIG_KAPASITE NUMBER NOT NULL,

    CONSTRAINT PK_DE_LIGLER
        PRIMARY KEY (LIG_ID),

    CONSTRAINT FK_LIGLER_FEDERASYON
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID)
);


/* =========================================================
   3. TAKIMLAR
   ========================================================= */

CREATE TABLE DE_TAKIMLAR (
    TAKIM_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ID NUMBER NOT NULL,
    TAKIM_ADI VARCHAR2(150) NOT NULL,
    LIG_ID NUMBER NOT NULL,

    CONSTRAINT PK_DE_TAKIMLAR
        PRIMARY KEY (TAKIM_ID),

    CONSTRAINT FK_TAKIM_FEDERASYON
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID),

    CONSTRAINT FK_TAKIM_LIG
        FOREIGN KEY (LIG_ID)
        REFERENCES DE_LIGLER(LIG_ID)
);


/* =========================================================
   4. OYUNCULAR
   ========================================================= */

CREATE TABLE DE_OYUNCULAR (
    OYUNCU_LISANS_NO NUMBER NOT NULL,
    OYUNCU_ADI_SOYADI VARCHAR2(150) NOT NULL,
    OYUNCU_DOGUM_YERI VARCHAR2(100) NOT NULL,
    OYUNCU_DOGUM_TARIHI DATE NOT NULL,
    TAKIM_ID NUMBER NOT NULL,
    OYUNCU_SOZLESME_BAS DATE DEFAULT SYSDATE NOT NULL,
    OYUNCU_SOZLESME_BITIS DATE NOT NULL,
    OYUNCU_LISANS_VERILIS_TARIHI DATE NOT NULL,
    OYUNCU_MEVKI VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_DE_OYUNCULAR
        PRIMARY KEY (OYUNCU_LISANS_NO),

    CONSTRAINT FK_OYUNCU_TAKIM
        FOREIGN KEY (TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID)
);


/* =========================================================
   5. MUSABAKA ALANLARI
   ========================================================= */

CREATE TABLE DE_MUSABAKA_ALANI (
    MUSABAKA_ALANI_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ID NUMBER NULL,
    MUSABAKA_ALANI_ADI VARCHAR2(150) NOT NULL,
    MUSABAKA_ALANI_ADRESI VARCHAR2(250) NOT NULL,
    MUSABAKA_ALANI_SEHIR VARCHAR2(100) NOT NULL,
    MUSABAKA_ALANI_KAPASITE NUMBER NOT NULL,
    ZEMIN_TURU VARCHAR2(100) NOT NULL,
    TAKIM_ID NUMBER NULL,

    CONSTRAINT PK_DE_MUSABAKA_ALANI
        PRIMARY KEY (MUSABAKA_ALANI_ID),

    CONSTRAINT FK_MUSABAKA_FED
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID),

    CONSTRAINT FK_MUSABAKA_TAKIM
        FOREIGN KEY (TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID)
);


/* =========================================================
   6. FIKSTUR
   ========================================================= */

CREATE TABLE DE_FIKSTUR (

    FIKSTUR_ID NUMBER
        GENERATED ALWAYS AS IDENTITY,

    FEDERASYON_ID NUMBER NOT NULL,

    LIG_ID NUMBER NOT NULL,

    HAFTA NUMBER NOT NULL,

    EV_SAHIBI_TAKIM_ID NUMBER NOT NULL,

    DEPLASMAN_TAKIM_ID NUMBER NOT NULL,

    MAC_TARIHI DATE NOT NULL,

    MUSABAKA_ALANI_ID NUMBER NOT NULL,

    MAC_SONUCU VARCHAR2(50)
        DEFAULT 'OYNANMADI'
        NOT NULL,

    ISLEM_TARIHI DATE
        DEFAULT SYSDATE,


    /* =========================
       PRIMARY KEY
       ========================= */

    CONSTRAINT PK_DE_FIKSTUR
        PRIMARY KEY (FIKSTUR_ID),


    /* =========================
       FOREIGN KEY'LER
       ========================= */

    CONSTRAINT FK_FIKSTUR_FEDERASYON
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID),


    CONSTRAINT FK_FIKSTUR_LIG
        FOREIGN KEY (LIG_ID)
        REFERENCES DE_LIGLER(LIG_ID),


    CONSTRAINT FK_FIKSTUR_EV_TAKIM
        FOREIGN KEY (EV_SAHIBI_TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID),


    CONSTRAINT FK_FIKSTUR_DEP_TAKIM
        FOREIGN KEY (DEPLASMAN_TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID),


    CONSTRAINT FK_FIKSTUR_MUSABAKA_ALANI
        FOREIGN KEY (MUSABAKA_ALANI_ID)
        REFERENCES DE_MUSABAKA_ALANI(MUSABAKA_ALANI_ID),


    /* =========================
       CHECK CONSTRAINT'LER
       ========================= */

    CONSTRAINT CHK_FIKSTUR_HAFTA
        CHECK (HAFTA > 0),


    CONSTRAINT CHK_FIKSTUR_TAKIM
        CHECK (
            EV_SAHIBI_TAKIM_ID
            <>
            DEPLASMAN_TAKIM_ID
        )

);
/


/* =========================================================
   7. HAKEM KLASMANLARI
   ========================================================= */

CREATE TABLE DE_HAKEM_KLASMAN (
    KLASMAN_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ID NUMBER NOT NULL,
    KLASMAN_TURU VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_DE_HAKEM_KLASMAN
        PRIMARY KEY (KLASMAN_ID),

    CONSTRAINT FK_KLASMAN_FED
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID)
);


/* =========================================================
   8. HAKEMLER
   ========================================================= */

CREATE TABLE DE_HAKEMLER (
    HAKEM_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ID NUMBER NOT NULL,
    HAKEM_ADI_SOYADI VARCHAR2(150) NOT NULL,
    KLASMAN_ID NUMBER NOT NULL,
    HAKEM_AKTIFLIK NUMBER(1) NOT NULL,
    HAKEM_ATANMA VARCHAR2(10) NOT NULL,

    CONSTRAINT PK_DE_HAKEMLER
        PRIMARY KEY (HAKEM_ID),

    CONSTRAINT FK_HAKEM_FED
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID),

    CONSTRAINT FK_HAKEM_KLASMAN
        FOREIGN KEY (KLASMAN_ID)
        REFERENCES DE_HAKEM_KLASMAN(KLASMAN_ID),

    CONSTRAINT CHK_HAKEM_AKTIFLIK
        CHECK (HAKEM_AKTIFLIK IN (0, 1)),

    CONSTRAINT CHK_HAKEM_ATANMA
        CHECK (HAKEM_ATANMA IN ('ATANDI', 'ATANMADI'))
);


/* =========================================================
   9. FIKSTUR - HAKEM
   Bir maçta birden fazla hakem bulunabileceði için ara tablo.
   ========================================================= */

CREATE TABLE DE_FIKSTUR_HAKEM (
    FIKSTUR_HAKEM_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FIKSTUR_ID NUMBER NOT NULL,
    HAKEM_ID NUMBER NOT NULL,
    HAKEM_GOREVI VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_DE_FIKSTUR_HAKEM
        PRIMARY KEY (FIKSTUR_HAKEM_ID),

    CONSTRAINT FK_FH_FIKSTUR
        FOREIGN KEY (FIKSTUR_ID)
        REFERENCES DE_FIKSTUR(FIKSTUR_ID),

    CONSTRAINT FK_FH_HAKEM
        FOREIGN KEY (HAKEM_ID)
        REFERENCES DE_HAKEMLER(HAKEM_ID),

    CONSTRAINT UK_FIKSTUR_HAKEM
        UNIQUE (FIKSTUR_ID, HAKEM_ID)
);


/* =========================================================
   10. FUTBOL PUAN DURUMU
   ========================================================= */

CREATE TABLE DE_FUTBOL_PUAN_DURUMU (
    FUTBOL_PD_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    TAKIM_ID NUMBER NOT NULL,
    GALIBIYET NUMBER NOT NULL,
    BERABERLIK NUMBER NOT NULL,
    MAGLUBIYET NUMBER NOT NULL,
    ATILAN_GOL NUMBER NOT NULL,
    YENILEN_GOL NUMBER NOT NULL,
    PUAN NUMBER NOT NULL,

    CONSTRAINT PK_FUTBOL_PD
        PRIMARY KEY (FUTBOL_PD_ID),

    CONSTRAINT FK_FUTBOL_PD_TAKIM
        FOREIGN KEY (TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID)
);


/* =========================================================
   11. BASKETBOL PUAN DURUMU
   ========================================================= */

CREATE TABLE DE_BASKETBOL_PUAN_DURUMU (
    BASKETBOL_PD_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    TAKIM_ID NUMBER NOT NULL,
    OYNANAN_MAC NUMBER NOT NULL,
    GALIBIYET NUMBER NOT NULL,
    MAGLUBIYET NUMBER NOT NULL,
    ATILAN_SAYI NUMBER NOT NULL,
    YENILEN_SAYI NUMBER NOT NULL,
    IC_AVERAJ NUMBER NOT NULL,
    IC_PUAN NUMBER NOT NULL,
    TOPLAM_AVERAJ NUMBER NOT NULL,
    PUAN NUMBER NOT NULL,

    CONSTRAINT PK_BASKETBOL_PD
        PRIMARY KEY (BASKETBOL_PD_ID),

    CONSTRAINT FK_BASKET_PD_TAKIM
        FOREIGN KEY (TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID)
);


/* =========================================================
   12. VOLEYBOL PUAN DURUMU
   ========================================================= */

CREATE TABLE DE_VOLEYBOL_PUAN_DURUMU (
    VOLEYBOL_PD_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    TAKIM_ID NUMBER NOT NULL,
    OYNANAN_MAC NUMBER NOT NULL,
    GALIBIYET NUMBER NOT NULL,
    MAGLUBIYET NUMBER NOT NULL,
    ALINAN_SET NUMBER NOT NULL,
    VERILEN_SET NUMBER NOT NULL,
    SET_ORANI NUMBER NOT NULL,
    ALINAN_SAYI_PUANI NUMBER NOT NULL,
    VERILEN_SAYI_PUANI NUMBER NOT NULL,
    SAYI_PUANI_ORANI NUMBER NOT NULL,
    PUAN NUMBER NOT NULL,

    CONSTRAINT PK_VOLEYBOL_PD
        PRIMARY KEY (VOLEYBOL_PD_ID),

    CONSTRAINT FK_VOLEYBOL_PD_TAKIM
        FOREIGN KEY (TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID)
);


/* =========================================================
   13. CEZA TURLERI
   ========================================================= */

CREATE TABLE DE_CEZA_TURU (
    CEZA_TURU_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ID NUMBER NOT NULL,
    CEZA_TURU_ADI VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_DE_CEZA_TURU
        PRIMARY KEY (CEZA_TURU_ID),

    CONSTRAINT FK_CEZA_TURU_FED
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID)
);


/* =========================================================
   14. SKOR LOG
   ========================================================= */

CREATE TABLE DE_SKOR_LOG (
    SKOR_LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ID NUMBER NOT NULL,
    FIKSTUR_ID NUMBER NOT NULL,
    MAC_TARIHI DATE NOT NULL,
    OYUNCU_LISANS_NO NUMBER NOT NULL,
    TAKIM_ID NUMBER NOT NULL,
    SKOR_TURU VARCHAR2(100) NOT NULL,
    SKOR_DEGERI NUMBER NOT NULL,
    DAKIKA NUMBER NULL,
    PERIYOT_SET NUMBER NULL,

    CONSTRAINT PK_DE_SKOR_LOG
        PRIMARY KEY (SKOR_LOG_ID),

    CONSTRAINT FK_SKOR_FED
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID),

    CONSTRAINT FK_SKOR_FIKSTUR
        FOREIGN KEY (FIKSTUR_ID)
        REFERENCES DE_FIKSTUR(FIKSTUR_ID),

    CONSTRAINT FK_SKOR_OYUNCU
        FOREIGN KEY (OYUNCU_LISANS_NO)
        REFERENCES DE_OYUNCULAR(OYUNCU_LISANS_NO),

    CONSTRAINT FK_SKOR_TAKIM
        FOREIGN KEY (TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID)
);


/* =========================================================
   15. CEZA LOG
   ========================================================= */

CREATE TABLE DE_CEZA_LOG (
    CEZA_LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FEDERASYON_ID NUMBER NOT NULL,
    FIKSTUR_ID NUMBER NOT NULL,
    MAC_TARIHI DATE NOT NULL,
    OYUNCU_LISANS_NO NUMBER NOT NULL,
    TAKIM_ID NUMBER NOT NULL,
    CEZA_TURU_ID NUMBER NOT NULL,
    DAKIKA NUMBER NULL,
    PERIYOT_SET NUMBER NULL,
    ACIKLAMA VARCHAR2(500) NULL,

    CONSTRAINT PK_DE_CEZA_LOG
        PRIMARY KEY (CEZA_LOG_ID),

    CONSTRAINT FK_CEZA_LOG_FED
        FOREIGN KEY (FEDERASYON_ID)
        REFERENCES DE_FEDERASYONLAR(FEDERASYON_ID),

    CONSTRAINT FK_CEZA_LOG_FIKSTUR
        FOREIGN KEY (FIKSTUR_ID)
        REFERENCES DE_FIKSTUR(FIKSTUR_ID),

    CONSTRAINT FK_CEZA_LOG_OYUNCU
        FOREIGN KEY (OYUNCU_LISANS_NO)
        REFERENCES DE_OYUNCULAR(OYUNCU_LISANS_NO),

    CONSTRAINT FK_CEZA_LOG_TAKIM
        FOREIGN KEY (TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID),

    CONSTRAINT FK_CEZA_LOG_TUR
        FOREIGN KEY (CEZA_TURU_ID)
        REFERENCES DE_CEZA_TURU(CEZA_TURU_ID)
);

/* =========================================================
   ORTAK MUSABAKA ALANI TABLOSU
   ========================================================= */

CREATE TABLE DE_ORTAK_MUSABAKA_ALANI (

    ORTAK_MUSABAKA_ALANI_ID NUMBER
        GENERATED ALWAYS AS IDENTITY,

    ORTAK_GRUP_NO NUMBER NOT NULL,

    MUSABAKA_ALANI_ID NUMBER NOT NULL,

    MUSABAKA_ALANI_ADI VARCHAR2(150) NOT NULL,

    TAKIM_ID NUMBER NOT NULL,

    TAKIM_ADI VARCHAR2(150) NOT NULL,

    ISLEM_TARIHI DATE DEFAULT SYSDATE,

    CONSTRAINT PK_DE_ORTAK_MUSABAKA
        PRIMARY KEY (ORTAK_MUSABAKA_ALANI_ID),

    CONSTRAINT FK_ORTAK_MUSABAKA_ALANI
        FOREIGN KEY (MUSABAKA_ALANI_ID)
        REFERENCES DE_MUSABAKA_ALANI(MUSABAKA_ALANI_ID),

    CONSTRAINT FK_ORTAK_MUSABAKA_TAKIM
        FOREIGN KEY (TAKIM_ID)
        REFERENCES DE_TAKIMLAR(TAKIM_ID),

    CONSTRAINT UK_ORTAK_MUSABAKA
        UNIQUE (MUSABAKA_ALANI_ID, TAKIM_ID)
);
/


ALTER TABLE DE_FEDERASYONLAR
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_LIGLER
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_TAKIMLAR
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_OYUNCULAR
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_MUSABAKA_ALANI
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_FIKSTUR
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_HAKEM_KLASMAN
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_HAKEMLER
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_FIKSTUR_HAKEM
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_FUTBOL_PUAN_DURUMU
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_BASKETBOL_PUAN_DURUMU
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_VOLEYBOL_PUAN_DURUMU
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_CEZA_TURU
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_SKOR_LOG
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_CEZA_LOG
ADD ISLEM_TARIHI DATE DEFAULT SYSDATE NULL;

ALTER TABLE DE_FEDERASYONLAR
MODIFY FEDERASYON_KURULUS_TARIHI DATE;

ALTER TABLE DE_FUTBOL_PUAN_DURUMU
ADD LIG_ID NUMBER;




ALTER TABLE DE_FUTBOL_PUAN_DURUMU
ADD LIG_ID NUMBER;

ALTER TABLE DE_FUTBOL_PUAN_DURUMU
ADD CONSTRAINT FK_FUTBOL_PD_LIG
FOREIGN KEY (LIG_ID)
REFERENCES DE_LIGLER(LIG_ID);




UPDATE DE_FUTBOL_PUAN_DURUMU P
SET P.LIG_ID = (
    SELECT T.LIG_ID
    FROM DE_TAKIMLAR T
    WHERE T.TAKIM_ID = P.TAKIM_ID
);

COMMIT;




ALTER TABLE DE_FUTBOL_PUAN_DURUMU
MODIFY LIG_ID NOT NULL;





ALTER TABLE DE_BASKETBOL_PUAN_DURUMU
ADD LIG_ID NUMBER;

ALTER TABLE DE_BASKETBOL_PUAN_DURUMU
ADD CONSTRAINT FK_BASKETBOL_PD_LIG
FOREIGN KEY (LIG_ID)
REFERENCES DE_LIGLER(LIG_ID);


UPDATE DE_BASKETBOL_PUAN_DURUMU P
SET P.LIG_ID = (
    SELECT T.LIG_ID
    FROM DE_TAKIMLAR T
    WHERE T.TAKIM_ID = P.TAKIM_ID
);

COMMIT;


ALTER TABLE DE_BASKETBOL_PUAN_DURUMU
MODIFY LIG_ID NOT NULL;





ALTER TABLE DE_VOLEYBOL_PUAN_DURUMU
ADD LIG_ID NUMBER;

ALTER TABLE DE_VOLEYBOL_PUAN_DURUMU
ADD CONSTRAINT FK_VOLEYBOL_PD_LIG
FOREIGN KEY (LIG_ID)
REFERENCES DE_LIGLER(LIG_ID);


UPDATE DE_VOLEYBOL_PUAN_DURUMU P
SET P.LIG_ID = (
    SELECT T.LIG_ID
    FROM DE_TAKIMLAR T
    WHERE T.TAKIM_ID = P.TAKIM_ID
);

COMMIT;


ALTER TABLE DE_VOLEYBOL_PUAN_DURUMU
MODIFY LIG_ID NOT NULL;


